package org.acme.ticket_support;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IssueList implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public IssueList() {
    }

}